uint8 SAVE_MAP=1
uint8 START_NAVIGATION=2
uint8 SAVE_AND_START_NAVIGATION=3
uint8 STOP_SESSION=4

uint8 command
---
bool success
string message
embodied_agent_interfaces/SlamSessionState state
---
float32 progress
embodied_agent_interfaces/SlamSessionState state
